import { BulkItem } from '../types';
import coffyBrandingPack from '../assets/images/coffy_branding_pack_1791019025042.jpg';
import coffyVectorArt from '../assets/images/coffy_vector_art_1791019002718.jpg';
import coffyCinemaFilm from '../assets/images/coffy_cinema_film_1791019014036.jpg';
import coffyMotionGraphics from '../assets/images/coffy_motion_graphics_1791019037281.jpg';

// Instant 1-Click Master Samples for Immediate Test-Drive (Full 49-Keyword Rank #1 Calibrated)
export const SAMPLE_SHOWCASE_ASSETS: {
  label: string;
  category: string;
  badge: string;
  item: BulkItem;
}[] = [
  {
    label: 'Modern Biophilic Villa at Sunset',
    category: 'Architecture & Living',
    badge: '49/49 SEO · $2.40 RPD',
    item: {
      id: 'demo-sample-1',
      file: new File([''], 'modern_biophilic_villa_sunset.jpg', { type: 'image/jpeg' }),
      previewUrl: coffyBrandingPack,
      status: 'completed',
      progress: 100,
      result: {
        recommendedTitle: 'Modern Biophilic Villa with Vertical Garden at Sunset',
        shortDescription: 'Contemporary sustainable luxury home featuring energy-efficient glass facade, vertical flora gardens, and warm golden hour ambient lighting.',
        category: 'Buildings and Architecture',
        commercialProblemSolved: 'Provides high-converting sustainable luxury real estate and ESG green architecture imagery for property developers and clean-tech brands.',
        longTailKeywords: [
          'modern biophilic architecture villa',
          'luxury eco friendly house sunset',
          'sustainable vertical garden facade',
          'energy efficient residential home',
          'contemporary green building design'
        ],
        priorityKeywords: [
          'biophilic architecture',
          'modern villa',
          'sustainable house',
          'vertical garden',
          'luxury real estate',
          'eco friendly home',
          'golden hour',
          'glass facade',
          'contemporary architecture',
          'energy efficient'
        ],
        keywords: [
          'biophilic architecture',
          'modern villa',
          'sustainable house',
          'vertical garden',
          'luxury real estate',
          'eco friendly home',
          'golden hour',
          'glass facade',
          'contemporary architecture',
          'energy efficient',
          'residential property',
          'green architecture',
          'wooden exterior',
          'terrace patio',
          'landscaping design',
          'architectural design',
          'clean technology',
          'scenic dusk',
          'smart home',
          'exterior photography',
          'outdoor deck',
          'sustainable development',
          'residential exterior',
          'luxurious living',
          'urban retreat',
          'natural materials',
          'passive house',
          'evening ambiance',
          'architectural visualization',
          'no people',
          'outdoors',
          'wide shot',
          'copy space',
          'modern lifestyle',
          'net zero building',
          'green roof',
          'solar integration',
          'biophilic design',
          'upscale neighborhood',
          'tropical minimalism',
          'travertine stone',
          'warm lighting',
          'real estate marketing',
          'property investment',
          'ecological living',
          'future living',
          'minimalist house',
          'commercial photography',
          'high resolution'
        ],
        keywordTaxonomy: {
          primarySubject: ['biophilic architecture', 'modern villa', 'sustainable house'],
          secondarySubject: ['vertical garden', 'glass facade', 'residential property'],
          action: ['living sustainably', 'architectural lighting', 'relaxing at dusk'],
          environment: ['outdoor terrace', 'luxury neighborhood', 'sunset exterior'],
          commercialConcept: ['sustainability', 'modern luxury', 'clean living', 'smart architecture'],
          useCases: ['real estate marketing', 'architectural magazine', 'sustainability presentation'],
          styleAndComposition: ['eye level wide shot', 'golden hour warm lighting', 'crisp symmetrical composition'],
          industry: ['Real Estate', 'Architecture & Design', 'Green Technology'],
          longTailPhrases: [
            'modern biophilic architecture home design',
            'luxury eco friendly villa at sunset',
            'sustainable energy efficient residential house',
            'vertical garden modern house exterior'
          ]
        },
        searchIntent: {
          primaryIntent: 'modern biophilic architecture villa',
          commercialUseCases: [
            'Luxury property developer marketing brochures',
            'Clean tech and solar architecture hero banners',
            'Interior design & green building editorial publications'
          ],
          targetBuyer: 'Real estate agencies, ESG corporate designers, architectural firms'
        },
        visualTruthConfidence: 'HIGH CONFIDENCE',
        metadataQualityScore: 99,
        technicalQualityScore: 98,
        salesPotentialScore: 97,
        acceptanceProbability: 98,
        overallSubmissionRiskScore: 4,
        riskLabel: 'Low risk',
        copyrightRiskScore: 0,
        explanation: 'All architectural features are generic contemporary design with zero visible logos, trademarks, or proprietary elements.',
        detectedDefects: []
      }
    }
  },
  {
    label: 'Automated Robotic Arm in Cleanroom',
    category: 'Enterprise AI & Tech',
    badge: '49/49 SEO · $3.90 RPD',
    item: {
      id: 'demo-sample-2',
      file: new File([''], 'industrial_robotics_semiconductor_cleanroom.jpg', { type: 'image/jpeg' }),
      previewUrl: coffyVectorArt,
      status: 'completed',
      progress: 100,
      result: {
        recommendedTitle: 'Automated Robotic Arm Working in Semiconductor Cleanroom',
        shortDescription: 'Industrial cybernetic robotic manipulator assembling delicate microelectronic semiconductor components in sterile high-tech laboratory.',
        category: 'Technology',
        commercialProblemSolved: 'Visualizes high-precision semiconductor manufacturing, industrial AI automation, and supply-chain resilience for B2B technology brands.',
        longTailKeywords: [
          'semiconductor cleanroom robotic arm',
          'automated microchip manufacturing plant',
          'industrial robotics precision assembly',
          'smart factory artificial intelligence',
          'silicon wafer production laboratory'
        ],
        priorityKeywords: [
          'industrial robotics',
          'semiconductor manufacturing',
          'robotic arm',
          'cleanroom facility',
          'microchip production',
          'precision automation',
          'artificial intelligence',
          'smart factory',
          'silicon wafer',
          'advanced manufacturing'
        ],
        keywords: [
          'industrial robotics',
          'semiconductor manufacturing',
          'robotic arm',
          'cleanroom facility',
          'microchip production',
          'precision automation',
          'artificial intelligence',
          'smart factory',
          'silicon wafer',
          'advanced manufacturing',
          'cyber physical system',
          'hi-tech electronics',
          'nanotechnology',
          'automated production',
          'machine learning',
          'futuristic technology',
          'circuit board',
          'robotic manipulator',
          'engineering innovation',
          'digital transformation',
          'industry 4.0',
          'mechatronics',
          'cleanroom laboratory',
          'wafer fabrication',
          'microelectronics',
          'autonomous machine',
          'tech infrastructure',
          'hardware engineering',
          'computer chip',
          'integrated circuit',
          'no people',
          'indoors',
          'close-up',
          'selective focus',
          'copy space',
          'sterile environment',
          'blue lighting',
          'corporate technology',
          'supply chain',
          'production line',
          'quality control',
          'laser precision',
          'semiconductor industry',
          'ai hardware',
          'deep tech',
          'factory automation',
          'modern industry',
          'commercial photography',
          'high resolution'
        ],
        keywordTaxonomy: {
          primarySubject: ['industrial robotics', 'robotic arm', 'microchip production'],
          secondarySubject: ['semiconductor manufacturing', 'cleanroom facility'],
          action: ['precision assembling', 'automated manufacturing', 'silicon processing'],
          environment: ['sterile laboratory', 'smart factory cleanroom', 'high tech facility'],
          commercialConcept: ['automation', 'industrial innovation', 'future of manufacturing', 'AI hardware'],
          useCases: ['tech enterprise website', 'semiconductor investor pitch', 'automation software hero banner'],
          styleAndComposition: ['macro depth of field', 'cool blue laboratory lighting', 'sharp mechanical detail'],
          industry: ['Semiconductor & Electronics', 'Industrial Automation', 'Artificial Intelligence'],
          longTailPhrases: [
            'automated robotic arm semiconductor manufacturing',
            'cleanroom microchip assembly precision robotics',
            'smart factory artificial intelligence manufacturing',
            'industrial cybernetic robotics laboratory technology'
          ]
        },
        searchIntent: {
          primaryIntent: 'semiconductor cleanroom robotic arm',
          commercialUseCases: [
            'Semiconductor investment deck',
            'Industrial IoT platform landing page',
            'Deep tech venture capital portfolio report'
          ],
          targetBuyer: 'Enterprise software companies, chip manufacturers, logistics tech providers'
        },
        visualTruthConfidence: 'HIGH CONFIDENCE',
        metadataQualityScore: 99,
        technicalQualityScore: 98,
        salesPotentialScore: 99,
        acceptanceProbability: 99,
        overallSubmissionRiskScore: 3,
        riskLabel: 'Low risk',
        copyrightRiskScore: 0,
        explanation: 'Mechanical structure is non-branded custom robotics with zero protected trademarks.',
        detectedDefects: []
      }
    }
  },
  {
    label: 'Coastal Offshore Wind Turbine Array',
    category: 'Renewable Clean Energy',
    badge: '49/49 SEO · $3.20 RPD',
    item: {
      id: 'demo-sample-3',
      file: new File([''], 'offshore_wind_turbines_ocean_renewable.jpg', { type: 'image/jpeg' }),
      previewUrl: coffyCinemaFilm,
      status: 'completed',
      progress: 100,
      result: {
        recommendedTitle: 'Offshore Wind Turbine Array Generating Clean Energy at Sea',
        shortDescription: 'Modern offshore wind power generation farm positioned in coastal waters producing sustainable green electricity under clear morning skies.',
        category: 'The Environment',
        commercialProblemSolved: 'Delivers authoritative ESG sustainability and carbon-neutral infrastructure imagery for annual corporate reports and utility campaigns.',
        longTailKeywords: [
          'offshore wind turbine farm',
          'renewable clean energy ocean',
          'sustainable green electricity grid',
          'carbon neutral wind power',
          'marine wind generator array'
        ],
        priorityKeywords: [
          'offshore wind turbine',
          'renewable energy',
          'wind farm',
          'green electricity',
          'clean power',
          'sustainable infrastructure',
          'ocean energy',
          'wind generator',
          'carbon neutral',
          'environmental sustainability'
        ],
        keywords: [
          'offshore wind turbine',
          'renewable energy',
          'wind farm',
          'green electricity',
          'clean power',
          'sustainable infrastructure',
          'ocean energy',
          'wind generator',
          'carbon neutral',
          'environmental sustainability',
          'alternative energy',
          'marine wind farm',
          'green power grid',
          'turbine blades',
          'clean technology',
          'electricity generation',
          'coastal landscape',
          'sustainable development',
          'power supply',
          'blue ocean',
          'climate action',
          'net zero emissions',
          'esg investing',
          'clean energy transition',
          'eco power',
          'natural resource',
          'wind energy',
          'energy independence',
          'offshore platform',
          'maritime engineering',
          'no people',
          'outdoors',
          'aerial view',
          'wide angle',
          'copy space',
          'morning sunlight',
          'clear sky',
          'calm sea',
          'horizon',
          'utility infrastructure',
          'future energy',
          'green economy',
          'environmental protection',
          'decarbonization',
          'power generation',
          'clean environment',
          'renewable power',
          'commercial photography',
          'high resolution'
        ],
        keywordTaxonomy: {
          primarySubject: ['offshore wind turbine', 'wind farm', 'renewable energy'],
          secondarySubject: ['ocean waters', 'wind turbine blades', 'clean power grid'],
          action: ['generating electricity', 'rotating turbine blades', 'harnessing wind power'],
          environment: ['coastal sea', 'open ocean waters', 'clear morning sky'],
          commercialConcept: ['clean energy transition', 'carbon neutrality', 'ESG investment', 'sustainable future'],
          useCases: ['ESG corporate annual report', 'clean energy investment presentation', 'environmental utility website'],
          styleAndComposition: ['aerial wide angle view', 'natural morning sunlight', 'serene calm horizon'],
          industry: ['Renewable Energy', 'Utilities & Power', 'Environmental Technology'],
          longTailPhrases: [
            'offshore wind turbine farm clean renewable energy',
            'sustainable green electricity marine wind power',
            'carbon neutral offshore wind power generation',
            'renewable energy infrastructure coastal ocean farm'
          ]
        },
        searchIntent: {
          primaryIntent: 'offshore wind turbine farm',
          commercialUseCases: [
            'Fortune 500 ESG sustainability report cover',
            'Clean utility provider web portal',
            'Renewable energy bond investor presentation'
          ],
          targetBuyer: 'Energy conglomerates, investment banks, environmental non-profits'
        },
        visualTruthConfidence: 'HIGH CONFIDENCE',
        metadataQualityScore: 99,
        technicalQualityScore: 97,
        salesPotentialScore: 98,
        acceptanceProbability: 99,
        overallSubmissionRiskScore: 2,
        riskLabel: 'Low risk',
        copyrightRiskScore: 0,
        explanation: 'Natural open landscape with standard industrial wind turbines; no proprietary brand marks.',
        detectedDefects: []
      }
    }
  },
  {
    label: 'Modern Tech Startup Team Vector Illustration',
    category: 'Vector / EPS Illustration',
    badge: '49/49 SEO · $3.80 RPD',
    item: {
      id: 'demo-sample-4',
      file: new File([''], 'modern_tech_startup_team_workspace.eps', { type: 'application/postscript' }),
      previewUrl: coffyMotionGraphics,
      status: 'completed',
      progress: 100,
      epsHint: {
        title: 'Modern Tech Startup Team Workspace Vector Illustration',
        creator: 'Adobe Illustrator Vector Engine',
        boundingBox: { x1: 0, y1: 0, x2: 1200, y2: 800, width: 1200, height: 800 },
        keywords: ['startup team', 'office collaboration', 'software developers', 'creative workspace', 'vector', 'eps']
      },
      result: {
        recommendedTitle: 'Tech Startup Team Collaborating in Office Vector Illustration',
        shortDescription: 'Flat modern vector illustration showing diverse software engineers and designers collaborating in a creative open-plan tech office workspace.',
        category: 'Graphic Resources',
        commercialProblemSolved: 'Gives SaaS companies, tech blogs, and HR teams a ready-to-scale EPS vector hero graphic illustrating agile teamwork and digital innovation.',
        longTailKeywords: [
          'tech startup team collaboration',
          'software developers office workspace',
          'flat design business teamwork',
          'creative agency brainstorming meeting',
          'isometric tech office vector'
        ],
        priorityKeywords: [
          'startup team',
          'office collaboration',
          'software developers',
          'creative workspace',
          'tech startup',
          'teamwork concept',
          'business meeting',
          'coding team',
          'digital innovation',
          'coworking space'
        ],
        keywords: [
          'startup team',
          'office collaboration',
          'software developers',
          'creative workspace',
          'tech startup',
          'teamwork concept',
          'business meeting',
          'coding team',
          'digital innovation',
          'coworking space',
          'ui ux designers',
          'agile workflow',
          'scrum meeting',
          'brainstorming',
          'business characters',
          'tech industry',
          'remote collaboration',
          'product development',
          'project management',
          'modern office',
          'diverse team',
          'corporate culture',
          'software engineering',
          'web development',
          'digital marketing',
          'saas platform',
          'entrepreneurship',
          'company growth',
          'workflow automation',
          'laptop computer',
          'strategy session',
          'creative agency',
          'landing page graphic',
          'app onboarding',
          'hero banner',
          'copy space',
          'clean composition',
          'vibrant colors',
          'isometric style',
          'flat design',
          'vector illustration',
          'scalable vector',
          'editable graphic',
          'commercial vector',
          'graphic template',
          'digital artwork',
          'modern illustration',
          'vector',
          'eps'
        ],
        keywordTaxonomy: {
          primarySubject: ['startup team', 'software developers', 'office workspace'],
          secondarySubject: ['laptop computer', 'creative studio', 'ui ux designers'],
          action: ['collaborating', 'coding', 'brainstorming', 'working'],
          environment: ['creative office', 'coworking space', 'modern interior'],
          commercialConcept: ['teamwork', 'digital innovation', 'business agility', 'tech growth'],
          useCases: ['SaaS marketing website', 'corporate recruitment banner', 'mobile app onboarding screen'],
          styleAndComposition: ['flat design vector', 'vibrant color palette', 'clean character art'],
          industry: ['Software & SaaS', 'Information Technology', 'Creative Agencies'],
          longTailPhrases: [
            'modern tech startup team vector illustration',
            'creative office collaboration flat vector graphic',
            'software developers brainstorming workspace vector',
            'digital business teamwork flat design illustration'
          ]
        },
        searchIntent: {
          primaryIntent: 'tech startup team collaboration',
          commercialUseCases: [
            'SaaS landing page hero illustration',
            'Mobile app welcome onboarding screen',
            'Corporate blog article header'
          ],
          targetBuyer: 'Web Designers, UI/UX Directors, Marketing Agencies & Product Managers'
        },
        visualTruthConfidence: 'HIGH CONFIDENCE',
        metadataQualityScore: 99,
        technicalQualityScore: 99,
        salesPotentialScore: 99,
        acceptanceProbability: 99,
        overallSubmissionRiskScore: 1,
        riskLabel: 'Low risk',
        copyrightRiskScore: 0,
        explanation: 'Clean original vector artwork with 100% commercially compliant graphic elements and subject-first Top 10 keyword locking.',
        detectedDefects: []
      }
    }
  }
];
