import React, { useState, useEffect, useRef } from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Sparkles, Copy, Check, Wand2, Camera, ShieldAlert, Tag, Lightbulb, RefreshCw, Layers } from 'lucide-react';
import { StockPromptResult } from '../types';

interface PromptStudioDashboardProps {
  onBack: () => void;
  customApiKey?: string;
  showToast: (msg: string) => void;
  initialConcept?: string;
  themeMode?: 'light' | 'dark';
}

const TRENDING_INSPIRATIONS = [
  'Futuristic solar farm engineers inspecting high-tech panels',
  'Autumn cozy coffee and cinnamon pastries flat lay on rustic wood',
  'Diverse multi-generational family cooking together in sunlit kitchen',
  'Minimalist modern ergonomic home office desk setup with warm plant',
  'Senior couple doing yoga in morning park with gentle golden hour light',
  'Electric vehicle charging station in clean European sustainable city',
];

export const PromptStudioDashboard: React.FC<PromptStudioDashboardProps> = ({
  onBack,
  customApiKey,
  showToast,
  initialConcept,
  themeMode = 'light',
}) => {
  const isLight = themeMode === 'light';
  const [concept, setConcept] = useState(initialConcept || '');
  const [style, setStyle] = useState('Commercial Stock Photography');
  const [aspectRatio, setAspectRatio] = useState('16:9');
  const [lighting, setLighting] = useState('Clean High-Key Commercial Daylight');
  const [shotType, setShotType] = useState('Medium shot with intentional copy space');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<StockPromptResult | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (initialConcept && initialConcept.trim() && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      setConcept(initialConcept.trim());
      handleGenerate(initialConcept.trim());
    }
  }, [initialConcept]);

  const handleGenerate = async (conceptToUse?: string) => {
    const finalConcept = (conceptToUse || concept).trim();
    if (!finalConcept) {
      showToast('Please type a photo concept or select an inspiration.');
      return;
    }

    setIsLoading(true);
    try {
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
      };
      if (customApiKey) {
        headers['x-api-key'] = customApiKey;
      }

      const res = await fetch('/api/generate-stock-prompt', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          concept: finalConcept,
          style,
          aspectRatio,
          lighting,
          shotType,
        }),
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to generate prompts');
      }

      const data: StockPromptResult = await res.json();
      setResult(data);
      showToast('✓ AI Stock Prompts generated successfully!');
    } catch (err: any) {
      console.error(err);
      showToast(err.message || 'Error generating prompts. Check API key in settings.');
    } finally {
      setIsLoading(false);
    }
  };

  const copyText = (text: string, keyName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(keyName);
    showToast(`Copied ${keyName} to clipboard!`);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="space-y-6"
    >
      {/* Top Header */}
      <div className={`flex items-center justify-between border p-5 sm:p-6 rounded-2xl transition-colors ${
        isLight
          ? 'bg-white border-neutral-200/90 text-neutral-900 shadow-2xs'
          : 'bg-[#111318] border-neutral-800 text-white shadow-xl'
      }`}>
        <div className="flex items-center gap-3.5">
          <button
            onClick={onBack}
            className={`p-2.5 rounded-xl border transition cursor-pointer ${
              isLight
                ? 'bg-[#fbfaf8] hover:bg-neutral-100 border-neutral-200 text-neutral-700'
                : 'bg-neutral-900 hover:bg-neutral-800 border-neutral-800 text-neutral-300'
            }`}
            title="Back to All Stores"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <div className="text-[10px] font-mono uppercase tracking-[0.18em] text-neutral-400">
              03 . STORE · AI PROMPT ENGINEERING LAB
            </div>
            <h1 className="text-lg sm:text-2xl font-bold tracking-tight flex items-center gap-2 mt-0.5">
              <Wand2 className="w-5 h-5 text-amber-500" />
              <span>AI Stock Prompt Creator</span>
            </h1>
            <p className={`text-xs mt-0.5 ${isLight ? 'text-neutral-500' : 'text-neutral-400'}`}>
              Generate commercial-grade prompts optimized to pass Adobe Stock, Shutterstock &amp; Midjourney review.
            </p>
          </div>
        </div>
      </div>

      {/* Input Form Card */}
      <div className={`border p-5 sm:p-6 rounded-2xl space-y-5 ${
        isLight
          ? 'bg-white border-neutral-200/90 text-neutral-900 shadow-2xs'
          : 'bg-[#111318] border-neutral-800 text-white shadow-xl'
      }`}>
        <div>
          <label className="text-[11px] font-mono font-bold uppercase tracking-[0.14em] text-neutral-400 block mb-2">
            Image Concept or Shoot Idea
          </label>
          <div className="flex flex-col sm:flex-row gap-2.5">
            <input
              type="text"
              value={concept}
              onChange={(e) => setConcept(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
              placeholder="e.g. Sustainable solar energy engineers in futuristic clean farm with copy space..."
              className={`flex-1 border rounded-xl px-4 py-3 text-sm focus:outline-none transition ${
                isLight
                  ? 'bg-[#fbfaf8] border-neutral-200/90 text-neutral-900 placeholder-neutral-400 focus:bg-white focus:border-neutral-900'
                  : 'bg-neutral-950 border-neutral-800 text-white placeholder-neutral-500 focus:border-neutral-600'
              }`}
            />
            <button
              onClick={() => handleGenerate()}
              disabled={isLoading || !concept.trim()}
              className={`font-bold text-xs sm:text-sm px-6 py-3 rounded-xl transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-40 ${
                isLight
                  ? 'bg-neutral-950 hover:bg-black text-white'
                  : 'bg-white hover:bg-neutral-200 text-neutral-950'
              }`}
            >
              {isLoading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" /> Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-amber-500" /> Generate Prompts
                </>
              )}
            </button>
          </div>
        </div>

        {/* Quick Inspiration Pills */}
        <div className="space-y-2">
          <span className="text-[11px] font-semibold text-neutral-400 flex items-center gap-1.5">
            <Lightbulb className="w-3.5 h-3.5 text-amber-500" /> Quick Stock Inspirations:
          </span>
          <div className="flex flex-wrap gap-2">
            {TRENDING_INSPIRATIONS.map((insp, idx) => (
              <button
                key={idx}
                onClick={() => {
                  setConcept(insp);
                  handleGenerate(insp);
                }}
                className={`text-xs border px-3 py-1.5 rounded-xl transition text-left cursor-pointer ${
                  isLight
                    ? 'bg-[#fbfaf8] hover:bg-neutral-100 border-neutral-200/90 text-neutral-700 hover:border-neutral-900'
                    : 'bg-neutral-900 hover:bg-neutral-800 border-neutral-800 text-neutral-300'
                }`}
              >
                {insp}
              </button>
            ))}
          </div>
        </div>

        {/* Options Grid */}
        <div className={`grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 pt-4 border-t ${
          isLight ? 'border-neutral-100' : 'border-neutral-800/80'
        }`}>
          <div>
            <label className="text-[10px] font-mono uppercase tracking-[0.14em] text-neutral-400 block mb-1.5">
              Style Format
            </label>
            <select
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              className={`w-full border text-xs rounded-xl p-2.5 font-medium focus:outline-none ${
                isLight
                  ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-900'
                  : 'bg-neutral-900 border-neutral-800 text-neutral-200'
              }`}
            >
              <option value="Commercial Stock Photography">Commercial Stock Photography</option>
              <option value="Authentic Candid Lifestyle">Authentic Candid Lifestyle</option>
              <option value="3D Isometric Render">3D Isometric Render</option>
              <option value="Minimal Flat Vector Illustration">Minimal Flat Vector</option>
              <option value="Editorial Photojournalism">Editorial Photojournalism</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-mono uppercase tracking-[0.14em] text-neutral-400 block mb-1.5">
              Aspect Ratio
            </label>
            <select
              value={aspectRatio}
              onChange={(e) => setAspectRatio(e.target.value)}
              className={`w-full border text-xs rounded-xl p-2.5 font-medium focus:outline-none ${
                isLight
                  ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-900'
                  : 'bg-neutral-900 border-neutral-800 text-neutral-200'
              }`}
            >
              <option value="16:9">16:9 (Landscape / Banner)</option>
              <option value="3:2">3:2 (Classic DSLR Frame)</option>
              <option value="4:5">4:5 (Social &amp; Mobile Vertical)</option>
              <option value="1:1">1:1 (Square Editorial)</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-mono uppercase tracking-[0.14em] text-neutral-400 block mb-1.5">
              Commercial Lighting
            </label>
            <select
              value={lighting}
              onChange={(e) => setLighting(e.target.value)}
              className={`w-full border text-xs rounded-xl p-2.5 font-medium focus:outline-none ${
                isLight
                  ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-900'
                  : 'bg-neutral-900 border-neutral-800 text-neutral-200'
              }`}
            >
              <option value="Clean High-Key Commercial Daylight">High-Key Daylight</option>
              <option value="Warm Golden Hour Sunlight">Golden Hour Glow</option>
              <option value="Softbox Studio Commercial Rim Light">Studio Softbox</option>
              <option value="Moody Cinematic Window Shadows">Moody Natural Shadows</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-mono uppercase tracking-[0.14em] text-neutral-400 block mb-1.5">
              Composition / Framing
            </label>
            <select
              value={shotType}
              onChange={(e) => setShotType(e.target.value)}
              className={`w-full border text-xs rounded-xl p-2.5 font-medium focus:outline-none ${
                isLight
                  ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-900'
                  : 'bg-neutral-900 border-neutral-800 text-neutral-200'
              }`}
            >
              <option value="Medium shot with intentional copy space">Medium Shot + Copy Space</option>
              <option value="Wide panoramic establishing angle">Wide Panoramic View</option>
              <option value="Close-up macro detail with blurred background">Macro Detail (f/1.8)</option>
              <option value="Top-down flat lay with negative space">Top-Down Flat Lay</option>
            </select>
          </div>
        </div>
      </div>

      {/* Results View */}
      {result && (
        <div className="space-y-4">
          {/* Engine Prompts Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Midjourney v6 Card */}
            <div className={`border rounded-2xl p-5 space-y-3 flex flex-col justify-between ${
              isLight ? 'bg-white border-neutral-200/90 shadow-2xs' : 'bg-[#111318] border-neutral-800 shadow-xl'
            }`}>
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className={`text-xs font-bold flex items-center gap-1.5 ${isLight ? 'text-neutral-900' : 'text-white'}`}>
                    <Camera className="w-4 h-4 text-amber-500" /> Midjourney v6.1
                  </span>
                  <span className="text-[10px] font-mono text-neutral-400">
                    --v 6.1 --style raw
                  </span>
                </div>
                <p className={`text-xs leading-relaxed font-mono p-3 rounded-xl border select-all ${
                  isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-800' : 'bg-neutral-950 border-neutral-800 text-neutral-300'
                }`}>
                  {result.midjourneyPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.midjourneyPrompt, 'Midjourney Prompt')}
                className={`w-full text-xs font-bold py-2.5 px-3 rounded-xl transition flex items-center justify-center gap-2 cursor-pointer ${
                  isLight ? 'bg-neutral-950 hover:bg-black text-white' : 'bg-white hover:bg-neutral-200 text-neutral-950'
                }`}
              >
                {copiedKey === 'Midjourney Prompt' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'Midjourney Prompt' ? 'Copied!' : 'Copy Midjourney Prompt'}</span>
              </button>
            </div>

            {/* Adobe Firefly Card */}
            <div className={`border rounded-2xl p-5 space-y-3 flex flex-col justify-between ${
              isLight ? 'bg-white border-neutral-200/90 shadow-2xs' : 'bg-[#111318] border-neutral-800 shadow-xl'
            }`}>
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className={`text-xs font-bold flex items-center gap-1.5 ${isLight ? 'text-neutral-900' : 'text-white'}`}>
                    <Sparkles className="w-4 h-4 text-emerald-500" /> Adobe Firefly Image 3
                  </span>
                  <span className="text-[10px] font-mono text-neutral-400">
                    Adobe Stock Friendly
                  </span>
                </div>
                <p className={`text-xs leading-relaxed font-mono p-3 rounded-xl border select-all ${
                  isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-800' : 'bg-neutral-950 border-neutral-800 text-neutral-300'
                }`}>
                  {result.fireflyPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.fireflyPrompt, 'Firefly Prompt')}
                className={`w-full text-xs font-bold py-2.5 px-3 rounded-xl transition flex items-center justify-center gap-2 cursor-pointer ${
                  isLight ? 'bg-neutral-950 hover:bg-black text-white' : 'bg-white hover:bg-neutral-200 text-neutral-950'
                }`}
              >
                {copiedKey === 'Firefly Prompt' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'Firefly Prompt' ? 'Copied!' : 'Copy Firefly Prompt'}</span>
              </button>
            </div>

            {/* Flux / SDXL Card */}
            <div className={`border rounded-2xl p-5 space-y-3 flex flex-col justify-between ${
              isLight ? 'bg-white border-neutral-200/90 shadow-2xs' : 'bg-[#111318] border-neutral-800 shadow-xl'
            }`}>
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className={`text-xs font-bold flex items-center gap-1.5 ${isLight ? 'text-neutral-900' : 'text-white'}`}>
                    <Layers className="w-4 h-4 text-amber-500" /> Flux.1 / SDXL
                  </span>
                  <span className="text-[10px] font-mono text-neutral-400">
                    Hyper-Realistic
                  </span>
                </div>
                <p className={`text-xs leading-relaxed font-mono p-3 rounded-xl border select-all ${
                  isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-800' : 'bg-neutral-950 border-neutral-800 text-neutral-300'
                }`}>
                  {result.fluxPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.fluxPrompt, 'Flux Prompt')}
                className={`w-full text-xs font-bold py-2.5 px-3 rounded-xl transition flex items-center justify-center gap-2 cursor-pointer ${
                  isLight ? 'bg-neutral-950 hover:bg-black text-white' : 'bg-white hover:bg-neutral-200 text-neutral-950'
                }`}
              >
                {copiedKey === 'Flux Prompt' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'Flux Prompt' ? 'Copied!' : 'Copy Flux Prompt'}</span>
              </button>
            </div>
          </div>

          {/* Negative Prompt & Commercial Rejection Shield Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Negative Prompt */}
            <div className={`border rounded-2xl p-4 sm:p-5 space-y-2.5 ${
              isLight ? 'bg-white border-neutral-200/90' : 'bg-[#111318] border-neutral-800'
            }`}>
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-rose-600 dark:text-rose-400 flex items-center gap-1.5">
                  <ShieldAlert className="w-4 h-4" /> Negative Prompt (Prevents Rejections)
                </span>
                <button
                  onClick={() => copyText(result.negativePrompt, 'Negative Prompt')}
                  className={`text-xs px-2.5 py-1 rounded-lg border transition flex items-center gap-1 cursor-pointer ${
                    isLight ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-700' : 'bg-neutral-900 border-neutral-800 text-neutral-300'
                  }`}
                >
                  {copiedKey === 'Negative Prompt' ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}
                  <span>Copy</span>
                </button>
              </div>
              <p className={`text-xs font-mono p-3 rounded-xl border ${
                isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-700' : 'bg-neutral-950 border-neutral-800 text-neutral-400'
              }`}>
                {result.negativePrompt}
              </p>
            </div>

            {/* Commercial Tips */}
            <div className={`border rounded-2xl p-4 sm:p-5 space-y-2.5 ${
              isLight ? 'bg-white border-neutral-200/90' : 'bg-[#111318] border-neutral-800'
            }`}>
              <span className="text-xs font-bold text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                <Lightbulb className="w-4 h-4" /> Commercial Buyer Advice
              </span>
              <p className={`text-xs leading-relaxed p-3 rounded-xl border ${
                isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-700' : 'bg-neutral-950 border-neutral-800 text-neutral-300'
              }`}>
                {result.commercialTips}
              </p>
            </div>
          </div>

          {/* Suggested Title and Keywords for this Prompt */}
          <div className={`border rounded-2xl p-5 space-y-3 ${
            isLight ? 'bg-white border-neutral-200/90' : 'bg-[#111318] border-neutral-800'
          }`}>
            <div className="flex items-center justify-between">
              <span className={`text-xs font-bold flex items-center gap-1.5 ${isLight ? 'text-neutral-900' : 'text-white'}`}>
                <Tag className="w-4 h-4 text-amber-500" /> Suggested Stock Title &amp; Keywords
              </span>
              <button
                onClick={() =>
                  copyText(
                    `Title: ${result.suggestedTitle || ''}\nKeywords: ${(result.suggestedKeywords || []).join(', ')}`,
                    'Metadata'
                  )
                }
                className={`text-xs font-semibold px-3 py-1.5 rounded-lg border transition flex items-center gap-1.5 cursor-pointer ${
                  isLight ? 'bg-[#fbfaf8] border-neutral-200 text-neutral-800 hover:bg-neutral-100' : 'bg-neutral-900 border-neutral-800 text-neutral-200 hover:bg-neutral-800'
                }`}
              >
                {copiedKey === 'Metadata' ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Title &amp; Keywords</span>
              </button>
            </div>

            <p className={`text-sm font-bold ${isLight ? 'text-neutral-900' : 'text-white'}`}>
              {result.suggestedTitle || 'Untitled Stock Visual'}
            </p>

            <div className="flex flex-wrap gap-1.5 pt-1">
              {(result.suggestedKeywords || []).map((kw, i) => (
                <span
                  key={i}
                  className={`text-[11px] px-2.5 py-1 rounded-lg border ${
                    isLight ? 'bg-[#fbfaf8] border-neutral-200/80 text-neutral-700' : 'bg-neutral-900 border-neutral-800 text-neutral-300'
                  }`}
                >
                  {kw}
                </span>
              ))}
            </div>
          </div>
        </div>
      )}
    </motion.div>
  );
};
