import React, { useState, useEffect, useRef } from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Sparkles, Copy, Check, Wand2, Camera, ShieldAlert, Tag, Lightbulb, RefreshCw, Layers } from 'lucide-react';
import { StockPromptResult } from '../types';

interface PromptStudioDashboardProps {
  onBack: () => void;
  customApiKey?: string;
  showToast: (msg: string) => void;
  initialConcept?: string;
}

const TRENDING_INSPIRATIONS = [
  'Futuristic solar farm engineers inspecting high-tech panels',
  'Autumn cozy coffee and cinnamon pastries flat lay on rustic wood',
  'Diverse multi-generational family cooking together in sunlit kitchen',
  'Minimalist modern ergonomic home office desk setup with warm plant',
  'Senior couple doing yoga in morning park with gentle golden hour light',
  'Electric vehicle charging station in clean European sustainable city',
];

export const PromptStudioDashboard: React.FC<PromptStudioDashboardProps> = ({
  onBack,
  customApiKey,
  showToast,
  initialConcept,
}) => {
  const [concept, setConcept] = useState(initialConcept || '');
  const [style, setStyle] = useState('Commercial Stock Photography');
  const [aspectRatio, setAspectRatio] = useState('16:9');
  const [lighting, setLighting] = useState('Clean High-Key Commercial Daylight');
  const [shotType, setShotType] = useState('Medium shot with intentional copy space');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<StockPromptResult | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (initialConcept && initialConcept.trim() && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      setConcept(initialConcept.trim());
      handleGenerate(initialConcept.trim());
    }
  }, [initialConcept]);

  const handleGenerate = async (conceptToUse?: string) => {
    const finalConcept = (conceptToUse || concept).trim();
    if (!finalConcept) {
      showToast('Please type a photo concept or select an inspiration.');
      return;
    }

    setIsLoading(true);
    try {
      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
      };
      if (customApiKey) {
        headers['x-api-key'] = customApiKey;
      }

      const res = await fetch('/api/generate-stock-prompt', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          concept: finalConcept,
          style,
          aspectRatio,
          lighting,
          shotType,
        }),
      });

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to generate prompts');
      }

      const data: StockPromptResult = await res.json();
      setResult(data);
      showToast('✓ AI Stock Prompts generated successfully!');
    } catch (err: any) {
      console.error(err);
      showToast(err.message || 'Error generating prompts. Check API key in settings.');
    } finally {
      setIsLoading(false);
    }
  };

  const copyText = (text: string, keyName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(keyName);
    showToast(`Copied ${keyName} to clipboard!`);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="space-y-6"
    >
      {/* Top Header */}
      <div className="flex items-center justify-between bg-slate-950/80 backdrop-blur-xl border border-slate-800 p-4 sm:p-5 rounded-2xl shadow-xl">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="p-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 rounded-xl transition"
            title="Back to Studio"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-lg sm:text-xl font-black text-white flex items-center gap-2">
              <Wand2 className="w-5 h-5 text-indigo-400" />
              AI Stock Prompt Creator
            </h1>
            <p className="text-xs text-slate-400">
              Generate commercial-grade prompts optimized to pass Adobe Stock, Shutterstock & Midjourney review
            </p>
          </div>
        </div>
      </div>

      {/* Input Form Card */}
      <div className="bg-slate-950/80 backdrop-blur-xl border border-slate-800 p-5 sm:p-6 rounded-2xl shadow-2xl space-y-4">
        <div>
          <label className="text-xs font-bold uppercase tracking-wider text-slate-400 block mb-2">
            Image Concept or Shoot Idea
          </label>
          <div className="flex flex-col sm:flex-row gap-2">
            <input
              type="text"
              value={concept}
              onChange={(e) => setConcept(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
              placeholder="e.g. Sustainable solar energy engineers in futuristic clean farm with copy space..."
              className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
            />
            <button
              onClick={() => handleGenerate()}
              disabled={isLoading || !concept.trim()}
              className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-800 disabled:text-slate-500 text-white font-bold text-sm px-6 py-3 rounded-xl transition flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/20"
            >
              {isLoading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" /> Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" /> Generate Prompts
                </>
              )}
            </button>
          </div>
        </div>

        {/* Quick Inspiration Pills */}
        <div className="space-y-1.5">
          <span className="text-[11px] font-semibold text-slate-400 flex items-center gap-1.5">
            <Lightbulb className="w-3.5 h-3.5 text-amber-400" /> Quick Stock Inspirations:
          </span>
          <div className="flex flex-wrap gap-2">
            {TRENDING_INSPIRATIONS.map((insp, idx) => (
              <button
                key={idx}
                onClick={() => {
                  setConcept(insp);
                  handleGenerate(insp);
                }}
                className="text-xs bg-slate-900 hover:bg-indigo-950/60 hover:text-indigo-300 hover:border-indigo-500/50 border border-slate-800 text-slate-300 px-3 py-1.5 rounded-lg transition text-left"
              >
                {insp}
              </button>
            ))}
          </div>
        </div>

        {/* Options Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 pt-3 border-t border-slate-800/80">
          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1.5">
              Style Format
            </label>
            <select
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-xs text-slate-200 rounded-lg p-2.5 focus:outline-none focus:border-indigo-500"
            >
              <option value="Commercial Stock Photography">Commercial Stock Photography</option>
              <option value="Authentic Candid Lifestyle">Authentic Candid Lifestyle</option>
              <option value="3D Isometric Render">3D Isometric Render</option>
              <option value="Minimal Flat Vector Illustration">Minimal Flat Vector</option>
              <option value="Editorial Photojournalism">Editorial Photojournalism</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1.5">
              Aspect Ratio
            </label>
            <select
              value={aspectRatio}
              onChange={(e) => setAspectRatio(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-xs text-slate-200 rounded-lg p-2.5 focus:outline-none focus:border-indigo-500"
            >
              <option value="16:9">16:9 (Landscape / Banner)</option>
              <option value="3:2">3:2 (Classic DSLR Frame)</option>
              <option value="4:5">4:5 (Social & Mobile Vertical)</option>
              <option value="1:1">1:1 (Square Editorial)</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1.5">
              Commercial Lighting
            </label>
            <select
              value={lighting}
              onChange={(e) => setLighting(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-xs text-slate-200 rounded-lg p-2.5 focus:outline-none focus:border-indigo-500"
            >
              <option value="Clean High-Key Commercial Daylight">High-Key Daylight</option>
              <option value="Warm Golden Hour Sunlight">Golden Hour Glow</option>
              <option value="Softbox Studio Commercial Rim Light">Studio Softbox</option>
              <option value="Moody Cinematic Window Shadows">Moody Natural Shadows</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1.5">
              Composition / Framing
            </label>
            <select
              value={shotType}
              onChange={(e) => setShotType(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-xs text-slate-200 rounded-lg p-2.5 focus:outline-none focus:border-indigo-500"
            >
              <option value="Medium shot with intentional copy space">Medium Shot + Copy Space</option>
              <option value="Wide panoramic establishing angle">Wide Panoramic View</option>
              <option value="Close-up macro detail with blurred background">Macro Detail (f/1.8)</option>
              <option value="Top-down flat lay with negative space">Top-Down Flat Lay</option>
            </select>
          </div>
        </div>
      </div>

      {/* Results View */}
      {result && (
        <div className="space-y-4">
          {/* Engine Prompts Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Midjourney v6 Card */}
            <div className="bg-slate-950/80 border border-indigo-500/30 rounded-2xl p-5 space-y-3 flex flex-col justify-between shadow-xl">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-black text-indigo-400 flex items-center gap-1.5">
                    <Camera className="w-4 h-4" /> Midjourney v6.1
                  </span>
                  <span className="text-[10px] bg-indigo-500/10 text-indigo-300 border border-indigo-500/20 px-2 py-0.5 rounded-full font-bold">
                    --v 6.1 --style raw
                  </span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed font-mono bg-slate-900/90 p-3 rounded-xl border border-slate-800 select-all">
                  {result.midjourneyPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.midjourneyPrompt, 'Midjourney Prompt')}
                className="w-full bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold py-2 px-3 rounded-xl transition flex items-center justify-center gap-2 shadow"
              >
                {copiedKey === 'Midjourney Prompt' ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
                <span>{copiedKey === 'Midjourney Prompt' ? 'Copied!' : 'Copy Midjourney Prompt'}</span>
              </button>
            </div>

            {/* Adobe Firefly Card */}
            <div className="bg-slate-950/80 border border-blue-500/30 rounded-2xl p-5 space-y-3 flex flex-col justify-between shadow-xl">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-black text-blue-400 flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4" /> Adobe Firefly Image 3
                  </span>
                  <span className="text-[10px] bg-blue-500/10 text-blue-300 border border-blue-500/20 px-2 py-0.5 rounded-full font-bold">
                    Adobe Stock Friendly
                  </span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed font-mono bg-slate-900/90 p-3 rounded-xl border border-slate-800 select-all">
                  {result.fireflyPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.fireflyPrompt, 'Firefly Prompt')}
                className="w-full bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold py-2 px-3 rounded-xl transition flex items-center justify-center gap-2 shadow"
              >
                {copiedKey === 'Firefly Prompt' ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
                <span>{copiedKey === 'Firefly Prompt' ? 'Copied!' : 'Copy Firefly Prompt'}</span>
              </button>
            </div>

            {/* Flux / SDXL Card */}
            <div className="bg-slate-950/80 border border-purple-500/30 rounded-2xl p-5 space-y-3 flex flex-col justify-between shadow-xl">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-black text-purple-400 flex items-center gap-1.5">
                    <Layers className="w-4 h-4" /> Flux.1 / SDXL
                  </span>
                  <span className="text-[10px] bg-purple-500/10 text-purple-300 border border-purple-500/20 px-2 py-0.5 rounded-full font-bold">
                    Hyper-Realistic
                  </span>
                </div>
                <p className="text-xs text-slate-300 leading-relaxed font-mono bg-slate-900/90 p-3 rounded-xl border border-slate-800 select-all">
                  {result.fluxPrompt}
                </p>
              </div>

              <button
                onClick={() => copyText(result.fluxPrompt, 'Flux Prompt')}
                className="w-full bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold py-2 px-3 rounded-xl transition flex items-center justify-center gap-2 shadow"
              >
                {copiedKey === 'Flux Prompt' ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
                <span>{copiedKey === 'Flux Prompt' ? 'Copied!' : 'Copy Flux Prompt'}</span>
              </button>
            </div>
          </div>

          {/* Negative Prompt & Commercial Rejection Shield Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Negative Prompt */}
            <div className="bg-slate-950/80 border border-rose-500/30 rounded-2xl p-4 sm:p-5 space-y-2.5">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-rose-400 flex items-center gap-1.5">
                  <ShieldAlert className="w-4 h-4" /> Negative Prompt (Prevents Rejections)
                </span>
                <button
                  onClick={() => copyText(result.negativePrompt, 'Negative Prompt')}
                  className="text-xs text-rose-300 hover:text-white bg-rose-950/60 border border-rose-800 px-2.5 py-1 rounded-lg transition flex items-center gap-1"
                >
                  {copiedKey === 'Negative Prompt' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>Copy</span>
                </button>
              </div>
              <p className="text-xs text-slate-400 font-mono bg-slate-900/70 p-3 rounded-xl border border-slate-800">
                {result.negativePrompt}
              </p>
            </div>

            {/* Commercial Tips */}
            <div className="bg-slate-950/80 border border-amber-500/30 rounded-2xl p-4 sm:p-5 space-y-2.5">
              <span className="text-xs font-bold text-amber-400 flex items-center gap-1.5">
                <Lightbulb className="w-4 h-4" /> Commercial Buyer Advice
              </span>
              <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/70 p-3 rounded-xl border border-slate-800">
                {result.commercialTips}
              </p>
            </div>
          </div>

          {/* Suggested Title and Keywords for this Prompt */}
          <div className="bg-slate-950/80 border border-slate-800 rounded-2xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-200 flex items-center gap-1.5">
                <Tag className="w-4 h-4 text-indigo-400" /> Suggested Stock Title & Keywords
              </span>
              <button
                onClick={() =>
                  copyText(
                    `Title: ${result.suggestedTitle || ''}\nKeywords: ${(result.suggestedKeywords || []).join(', ')}`,
                    'Metadata'
                  )
                }
                className="text-xs text-slate-300 hover:text-white bg-slate-800 border border-slate-700 px-3 py-1.5 rounded-lg transition flex items-center gap-1.5"
              >
                {copiedKey === 'Metadata' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Title & Keywords</span>
              </button>
            </div>

            <p className="text-sm font-bold text-indigo-300">{result.suggestedTitle || 'Untitled Stock Visual'}</p>

            <div className="flex flex-wrap gap-1.5 pt-1">
              {(result.suggestedKeywords || []).map((kw, i) => (
                <span
                  key={i}
                  className="text-[11px] bg-slate-900 border border-slate-800 text-slate-300 px-2 py-0.5 rounded-md"
                >
                  {kw}
                </span>
              ))}
            </div>
          </div>
        </div>
      )}
    </motion.div>
  );
};
